project:
  type: website
  render: 
    - docs/**/*.qmd

website:
  title: "SSP Cloud - Documentation"
  navbar:
    left:
      - href: docs/fr/discover.html
        text: Découverte du Datalab

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
