profile:
  default: fr

project:
  type: website
  render:
    - 'content/*.qmd'

website:
  title: "SSP Cloud - Documentation"
  sidebar:
    style: 'docked'

format:
  html:
    theme: 
      - darkly
      - styles.scss
