website:
  navbar:
    left:
      - text: "Découvrir le Datalab"
        menu:
          - text: "Principes"
            href: content/principles.qmd
          - text: "Premiers pas"
            href: index.qmd
      - text: "Utiliser le Datalab"
        menu:
          - text: "Contrôle de version"
            href: content/version-control.qmd
          - text: "Stockage de données"
            href: content/storage.qmd
          - text: "Gestion des secrets"
            href: content/secrets.qmd
          - text: "Configuration des services"
            href: content/services-configuration.qmd
      - text: "Créer un tuto"
        menu:
        - text: "Introduction"
          href: content/tutorials/introduction.qmd
        - text: "Choisir un support"
          href: content/tutorials/choose-materials.qmd
        - text: "Structurer le cours"
          href: content/tutorials/course-structure.qmd
        - text: "Configurer l'environnement"
          href: content/tutorials/set-up-environment.qmd