project:
  output-dir: _site/en

website:
  navbar:
    left:
      - text: "Discover the Datalab"
        menu:
          - text: "Principles"
            href: content/principles.qmd
          - text: "First steps"
            href: index.qmd
      - text: "Use the Datalab"
        menu:
          - text: "Version control"
            href: content/version-control.qmd
          - text: "Data storage"
            href: content/storage.qmd
          - text: "Managing secrets"
            href: content/secrets.qmd
          - text: "Services configuration"
            href: content/services-configuration.qmd
      - text: "Create a tutorial"
        menu: 
        - text: "Introduction"
          href: content/tutorials/introduction.qmd
        - text: "Choose a material"
          href: content/tutorials/choose-materials.qmd
        - text: "Course structure"
          href: content/tutorials/course-structure.qmd
        - text: "Set up an environment"
          href: content/tutorials/set-up-environment.qmd