website:
  sidebar:
    contents:
      - section: "Découvrir le Datalab"
        contents:
          - text: "Principes"
            href: content/principles.qmd
          - text: "Premiers pas"
            href: content/discover.qmd
      - section: "Utiliser le Datalab"
        contents:
          - text: "Contrôle de version"
            href: content/version-control.qmd
          - text: "Stockage de données"
            href: content/storage.qmd
          - text: "Gestion des secrets"
            href: content/secrets.qmd
          - text: "Configuration des services"
            href: content/services-configuration.qmd
