project:
  type: website
  render:
    - '*.qmd'

profile:
  group: [fr, en]
  default: fr

website:
  title: "docs.sspcloud.fr"
  favicon: assets/onyxia.svg
  navbar:
    title: "docs.sspcloud.fr"
    logo: assets/onyxia.png
    right:
      - icon: github
        href: https://github.com/InseeFrLab/docs.sspcloud.fr

format:
  html:
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
