project:
  type: website
  output-dir: ./_site/fr

website:
  title: "SSP Cloud - Documentation"
  navbar:
    left:
      - href: docs/principles.qmd
        text: Principes du Datalab
    right:
      - href: ../fr
        text: French
      - href: ../en
        text: English

lang: fr

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
