project:
  type: website
  output-dir: ./_site

website:
  title: "SSP Cloud - Documentation"
  navbar:
    left:
      - href: docs/principles.qmd
        text: Principes du Datalab
      - href: docs/discover.qmd
        text: Premiers pas avec le Datalab
      - href: docs/version-control.qmd
        text: Contrôle de version
      - href: docs/secrets.qmd
        text: Gestion des secrets
    right:
      - href: ../fr
        text: French
      - href: ../en
        text: English

lang: fr

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
