project:
  type: website
  output-dir: ./_site/en

website:
  title: "SSP Cloud - Documentation"
  navbar:
    left:
      - href: docs/principles.qmd
        text: Principles of the Datalab  
    right:
      - href: ../fr
        text: French
      - href: ../en
        text: English

lang: en

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
