project:
  type: website
  render:
    - '*.qmd'

profile:
  group: [fr, en]
  default: fr

website:
  title: "SSP Cloud - Documentation"
  sidebar:
    style: 'floating'

format:
  html:
    theme:
      dark: [darkly, _assets/scss/styles.scss]
      light: flatly
