name: Publish slides

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render FR version
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: fr
      - name: Render EN version
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: en
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          render: false
          target: gh-pages
