name: Publish slides

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render
        run: |
          quarto render --profile fr
          quarto render --profile en
      - name: Publish
        run: |
          git config --global user.email quarto-github-actions-publish@example.com
          git config --global user.name "Quarto GHA Workflow Runner"
          git add -Af .
          git commit --allow-empty -m "Built site for gh-pages"
          git push --force origin HEAD:gh-pages
